EmergenceResponse.Web/Areas/Config/Pages/Users/Details.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergenceResponse.Web.Areas.Config.Pages.Users
{
    public class DetailsModel : SysPageModel
    {
        public Member Member { get; set; }
        public void OnGet()
        {
            Member = Db.Members.FirstOrDefault(m => m.Id == CurrentUser.MemberId);

            PageTitle = Title = Member.Name;

        }
    }
}

EmergenceResponse.Web/Areas/Emergencies/Pages/Add.cshtml.cs
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergenceResponse.Web.Areas.Emergencies.Pages
{
    public class AddModel : SysPageModel
    {
        public void OnGet()
        {
        }
    }
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Add.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Lib;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;


namespace EmergenceResponse.Web.Areas.EmergencyReports.Pages
{
    public class AddModel : SysPageModel
    {
        [BindProperty]
        public Emergency Emergency { get; set; }
        [BindProperty]
        public Location Location { get; set; }   
        public EmergencyType? EType { get;set; }
        public void OnGet(EmergencyType? etype)
        {
            if(etype != null)
                EType = (EmergencyType)etype;

        }
        public async Task<IActionResult> OnPost()
        {
            Location.Id = Guid.NewGuid();
            Db.Locations.Add(Location);

            Emergency.Id = Guid.NewGuid();
            Emergency.CreationDate = DateTime.Now;
            Emergency.CreatorId = (Guid)CurrentUser.MemberId;
            Emergency.LocationId = Location.Id;
            Emergency.StatusId = (int)EmergencyStatus.UNASSIGNED;

            Db.Emergencies.Add(Emergency);
            await Db.SaveChangesAsync();

            await GetDistance(Location, Emergency);

            return Redirect("/Index");
        }

       
        public async Task<Data.ServiceProvider> GetDistance(Location origin, Emergency em)
        {
            var apiKey = "";
            var dests = Db.ServiceProviders.Include(c => c.Location).Where(c => c.TypeId == em.TypeId).ToList();

            var distances = new List<double>();

            foreach (var dest in dests)
            {
                using (var client = new HttpClient())
                {

                    var distanceResponse = await client.GetAsync($"https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins={origin.Latitude},{origin.Longitude}&destinations={dest.Location.Latitude},{dest.Location.Longitude}&key={apiKey}");
                    var distanceContent = await distanceResponse.Content.ReadAsStringAsync();
                    var distance = JObject.Parse(distanceContent)["rows"][0]["elements"][0]["distance"]["value"];

                    distances.Add((double)distance); // Convert meters to miles
                }
            }
            var sp = dests[distances.IndexOf(distances.Min())];
            em.ServiceProviderId = sp.Id;
            em.StatusId = (int)EmergencyStatus.ASSIGNED;

            if (await TryUpdateModelAsync(em, nameof(Emergency), c => c.ServiceProviderId, c => c.StatusId))
            {
                await Db.SaveChangesAsync();

            }
            return sp;           
        }
    }
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Details.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Lib;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EmergenceResponse.Web.Areas.EmergencyReports.Pages
{
    public class DetailsModel : SysPageModel
    {
        public Emergency Emergency { get; set; }
        public void OnGet(Guid id)
        {
            Emergency = Db.Emergencies
                .Include(c => c.Creator)
                .Include(c => c.ServiceProvider)
                .Include(c => c.Location)
                .FirstOrDefault(c => c.Id == id);
            PageTitle = Emergency.Description;
        }
        public async Task<IActionResult> OnPostApprove(Guid id)
        {
            Emergency = Db.Emergencies.Find(id);
            Emergency.StatusId = (int)EmergencyStatus.ASSIGNMENT_APPROVED;
            Emergency.ApprovalDate = DateTime.Now;
            Db.Update(Emergency);
            await Db.SaveChangesAsync();

            return RedirectToPage("Details", id);
        }
    }
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Direction.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EmergenceResponse.Web.Areas.EmergencyReports.Pages
{
    public class DirectionModel : SysPageModel
    {
        public Emergency Emergency { get; set; }
        public async Task OnGet(Guid id)
        {
            Emergency = await Db.Emergencies
                .Include(c => c.Creator)
                .Include(c => c.ServiceProvider).ThenInclude(c => c.Location)
                .Include(c => c.Location)
                .FirstAsync(c => c.Id == id);

            PageTitle = $"{Emergency.ServiceProvider.Name} to {Emergency.Location.Address + " " + Emergency.Location.City}";
        }
    }
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Index.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace EmergenceResponse.Web.Areas.EmergencyReports.Pages
{
    public class IndexModel : SysListPageModel<Emergency>
    {
        public void OnGet(int? p, int? ps, Guid? spId)
        {
            var query = Db.Emergencies.Include(c => c.Creator).Include(c => c.ServiceProvider).AsQueryable();

            if(CurrentUser.MemberId != null)
            {
                query = query.Where(c => c.CreatorId == CurrentUser.MemberId);
            }

            if(spId != null)
            {
                query = query.Where(c => c.ServiceProviderId == spId);
            }
            List = query.OrderByDescending(c => c.CreationDate).ToPagedList(p ?? 1, ps ?? DefaultPageSize);

            PageTitle = $"{List.Count} Emergence{ (List.Count==1 ? "" : "s")} Reported";
        }
    }
}

EmergenceResponse.Web/Areas/Members/Pages/Details.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EmergenceResponse.Web.Areas.Members.Pages
{
    public class DetailsModel : SysPageModel
    {
        public Member Member { get; set; }
        public void OnGet(Guid id)
        {
            Member = Db.Members.FirstOrDefault(c => c.Id == id);
            Title = PageTitle = Member.Name;
            
        }
    }
}

EmergenceResponse.Web/Areas/ServiceProviders/Pages/Add.cshtml.cs
using EmergenceResponse.Data;
using EmergenceResponse.Lib;
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EmergenceResponse.Web.Areas.ServiceProviders.Pages
{
    public class AddModel : SysPageModel
    {
        [BindProperty]
        public Data.ServiceProvider ServiceProvider { get; set; }
        [BindProperty]
        public Location Location{get;set;}
        public void OnGet()
        {
            Title = PageTitle = "Add service provider";
        }
        public async Task<IActionResult> OnPost()
        {
            Location.Id = Guid.NewGuid();
            Db.Locations.Add(Location);

            ServiceProvider.Id = Guid.NewGuid();
            ServiceProvider.CreationDate = DateTime.Now;
            
            ServiceProvider.LocationId = Location.Id;
            ServiceProvider.StatusId = (int)ServiceProviderStatus.AWAITING_ACTIVATION;
            

            Db.ServiceProviders.Add(ServiceProvider);
            await Db.SaveChangesAsync();

            return RedirectToPage("Details", new {id = ServiceProvider.Id});
        }
    }
}

EmergenceResponse.Web/Areas/ServiceProviders/Pages/Details.cshtml.cs
using EmergenceResponse.Web.Pages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace EmergenceResponse.Web.Areas.ServiceProviders.Pages
{
    public class DetailsModel : SysPageModel
    {
        public Data.ServiceProvider ServiceProvider { get; set; }
        public void OnGet(Guid id)
        {
            ServiceProvider = Db.ServiceProviders.Include(c => c.Location).FirstOrDefault(c => c.Id == id);
            Title = PageTitle = ServiceProvider.Name;
        }
    }
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Add.cshtml
@page

@model AddModel


<div class="container py-3">
    <h1 class="text-center mb-4">Emergency Report</h1>
    <div class="row">
        <div class="col-md-6">
            <div id="map" style="height: 500px"></div>
        </div>
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <form method="post">
              <div class="row">
                  <div class="col-md">
                      <div class="mb-3">
                        <label for="location" class="form-label">Longitude:</label>
                        <input asp-for="Location.Longitude" class="form-control" id="longitude" required>
                      </div>
                  </div>
                  <div class="col-md">
                      <div class="mb-3">
                        <label for="location" class="form-label">Latitude:</label>
                        <input asp-for="Location.Latitude" class="form-control" id="latitude" required>
                      </div>
                  </div>
              </div>            
                <div class="row">
                    <div class="col-md">
                        <div class="mb-3">
                            <label for="location" class="form-label">City:</label>
                            <input asp-for="Location.City" class="form-control" id="city" required>
                          </div>
                         
                    </div>
                    <div class="col-md">
                         <div class="mb-3">
                            <label for="location" class="form-label">Address:</label>
                            <textarea asp-for="Location.Address" class="form-control" rows="2" required></textarea>
                          </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="description" class="form-label">Emergency:</label>
                    
                    <select asp-for="Emergency.TypeId" class="form-select" asp-items="@Html.GetListItems<EmergencyType>()">
                        @if (Model.EType==null)
                        {
                            <option value="" disabled selected>Select type...</option>
                        }
                        else
                        {
                            <option value="@((int) Model.EType)" selected>@Model.EType.ToEnumString()</option>
                        }

                    </select>
                    <span asp-validation-for="Emergency.TypeId" class="text-danger"></span>
                </div>
              <div class="mb-3">
                <label for="description" class="form-label">Description:</label>
                <textarea asp-for="Emergency.Description" class="form-control" id="description" rows="4" required></textarea>
              </div>
              <div class="card-footer text-end">
                  <button type="submit" class="btn btn-success text-end">Submit Report</button>
              </div>
              
            </form>
                </div>
            </div>
            
        </div>     
    </div>
</div>

@section Scripts{
   @* <script>
        navigator.geolocation.getCurrentPosition(position => {
            const { latitude, longitude } = position.coords;
            map.innerHTML = '<iframe width="700" height="300" src="https://maps.google.com/maps?q='+latitude+','+longitude+'&amp;z=15&amp;output=embed"></iframe>'
        });
    </script>*@
    
    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 0, lng: 0},
                zoom: 15
            });
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    }; 

                    $('#longitude').val(pos.lng);
                    $('#latitude').val(pos.lat);
                    getCityName(pos.lat, pos.lng);

                    var marker = new google.maps.Marker({
                        position: pos,
                        map: map,
                        title: 'Current Location'
                    });
                    map.setCenter(pos);
                }, function() {
                    handleLocationError(true, infoWindow, map.getCenter());
                });
            } else {
                handleLocationError(false, infoWindow, map.getCenter());
            }
        }

        function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
            infoWindow.open(map);
        }

        function getCityName(lat, lng) {
          var geocoder = new google.maps.Geocoder();
          var latlng = new google.maps.LatLng(lat, lng);
          geocoder.geocode({'latLng': latlng}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
              if (results[0]) {
                for (var i = 0; i < results[0].address_components.length; i++) {
                  var component = results[0].address_components[i];
                  if (component.types.indexOf('locality') > -1) {
                    var cityName = component.long_name;
                    console.log(cityName);
                    $('#city').val(cityName);
                    return cityName;
                  }
                }
              } else {
                console.log('No results found');
              }
            } else {
              console.log('Geocoder failed due to: ' + status);
            }
          });
        }

        function getDistance(origin, destination) {
          var service = new google.maps.DistanceMatrixService();
          service.getDistanceMatrix({
            origins: [origin],
            destinations: [destination],
            travelMode: google.maps.TravelMode.DRIVING,
            unitSystem: google.maps.UnitSystem.METRIC,
            avoidHighways: false,
            avoidTolls: false
          }, function(response, status) {
            if (status == google.maps.DistanceMatrixStatus.OK && response.rows[0].elements[0].status != "ZERO_RESULTS") {
              var distance = response.rows[0].elements[0].distance.text;
              console.log(distance);
              return distance;
            } else {
              console.log("Unable to calculate distance.");
            }
          });
        }


    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=&callback=initMap"></script>

}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Details.cshtml
@page "{id}"
@model DetailsModel

@section breadcrumb {
    <a class="breadcrumb-item" asp-page="Index">Emergency</a>
    <a class="breadcrumb-item" asp-page=".">@Model.Emergency.CreationDate</a>
}
@section action{
    
    <div class="d-flex">   
        @if(Model.Emergency.StatusId == (int)EmergencyStatus.ASSIGNED)
        {
         <form method="post">
             <button class="ms-2 btn btn-success" asp-page="Details" asp-page-handler="Approve" asp-route-id="@Model.Emergency.Id"><i class="fa-solid fa-check"></i> Approve</button>
        </form>   
        }    
        @if(Model.CurrentUser.ServiceProviderId != null)
        {
            <a class="btn btn-primary" asp-page="Direction" asp-route-id="@Model.Emergency.Id"><i class="fa-solid fa-diamond-turn-right"></i> Get directions</a>
        }    
    </div>    
}

    <div class="row">
    <div class="col-md-12">
        <div class="card shadow">
            <div class="card-body">
                
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Description</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Description</div></div>
                </div>
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Creator</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Creator.Name</div></div>
                </div>
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Status</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Status.ToEnumString()</div></div>
                </div>
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Service provider</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.ServiceProvider.Name</div></div>
                </div>  
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Address</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Location.Address</div></div>
                </div> 
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Latitude</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Location.Latitude</div></div>
                    
                </div>
                <div class="row mb-3">
                    <label class="col-md-3 text-muted">Longitude</label>
                    <div class="col-md-9"><div class="label-value">@Model.Emergency.Location.Longitude</div></div>
                    
                </div>
                @if(Model.Emergency.StatusId == (int)EmergencyStatus.ASSIGNMENT_APPROVED || Model.Emergency.StatusId == (int)EmergencyStatus.COMPLETED)
                {
                    <div class="row mb-3">
                        <label class="col-md-3 text-muted">Response time</label>
                        <div class="col-md-9"><div class="label-value">@Model.Emergency.ResponceTime</div></div>
                    
                    </div>
                }
            </div>
            <div class="card-footer small text-muted">
                <div class="">Creation date</div>
                <div class="">@Model.Emergency.CreationDate</div>
            </div>
        </div> 
        
    </div>
</div>


@section sidebar{

}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Direction.cshtml
@page
@model DirectionModel
@section breadcrumb {
    <a class="breadcrumb-item" asp-page="Index">Emergency</a>
    <a class="breadcrumb-item" asp-page="Details" asp-route-id="@Model.Emergency.Id">@Model.Emergency.CreationDate</a>
    <a class="breadcrumb-item" asp-page=".">Directions</a>
}
<div id="map" style="height: 500px; width: 100%;}"></div>

<div id="org-lat" class="">@Model.Emergency.ServiceProvider.Location.Latitude</div>
<div id="org-long" class="">@Model.Emergency.ServiceProvider.Location.Longitude</div>
<div id="dest-lat" class="">@Model.Emergency.Location.Latitude</div>
<div id="dest-long" class="">@Model.Emergency.Location.Longitude</div>


@section Scripts{
    
     <script>
        function initMap() {
          const directionsService = new google.maps.DirectionsService();
          const directionsRenderer = new google.maps.DirectionsRenderer();
          const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 7,
            center: { lat: 41.85, lng: -87.65 },
          });
          directionsRenderer.setMap(map);

        var start_lat = parseFloat(document.getElementById('org-lat').innerText);
        var start_long = parseFloat(parseFloat(document.getElementById('org-long').innerText));
        var end_lat = parseFloat(document.getElementById('dest-lat').innerText);
        var end_long = parseFloat(parseFloat(document.getElementById('dest-long').innerText));

            console.log(start_lat, start_long, end_lat, end_long);

          const start = new google.maps.LatLng(start_lat, start_long);
          const end = new google.maps.LatLng(end_lat, end_long);

          const request = {
            origin: start,
            destination: end,
            travelMode: google.maps.TravelMode.DRIVING
          };

          directionsService.route(request, function(result, status) {
            if (status == google.maps.DirectionsStatus.OK) {
              directionsRenderer.setDirections(result);
            }
          });
        }
  </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=&callback=initMap"
    async defer></script>
}

EmergenceResponse.Web/Areas/EmergencyReports/Pages/Index.cshtml
@page
@model IndexModel
@section breadcrumb {
    <a class="breadcrumb-item" asp-page=".">Emergencies</a>  
}
@if(Model.CurrentUser.MemberId != null){
    @section action{
        <a asp-page="Add" class="btn btn-primary"><i class="fa fa-add"></i> Report now..</a>
    }
}

<table class="table table-sm table-striped table-hover mt-2 border-bottom border-top">
    <tr>
        <th>Date</th>
        <th>Created by</th>
        <th>Category</th>
        <th>Status</th>
        <th>Service provider</th>
    </tr>
    @foreach(var item in @Model.List)
    {
        <tr>
            <td><a asp-page="Details" asp-route-id="@item.Id">@item.CreationDate</a></td>
            <td>@item.Creator.Name</td>
            <td>@item.Type</td>
            <td class="small">@item.Status.ToEnumString()</td>
            <td>@item.ServiceProvider?.Name</td>
        </tr>       
    }                 
</table>

@if(Model.CurrentUser.MemberId != null){
    @section Sidebar{}
}